baseURL = "https://callumgwtaylor.github.io/"
languageCode = "en-us"
title = "CallumGWTaylor"
theme = "callum"
publishDir = "docs"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
[params]
  showAllPostsOnHomePage = true
  rss = true
  mathjax = true
  showProjectsList = true
  googleAnalytics = "UA-100075448-1"
  description = "🩺 : Intensive Care Trainee in West of Scotland 🎓: Currently Studying for MA Medical Ethics and Law @ Keele Uni"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 4

[[params.social]]
  name = "github"
  link = "https://github.com/callumgwtaylor"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/callumgwt"
