---
title: 'Mini Package: hdxr'
author: 'Callum Taylor'
date: '2017-06-04'
slug: mini-package-hdxr
categories: []
tags: []
Categories: R, hdxr. hdx, package
Description: ''
Tags: R. hdxr, hdx, package
---

### Mini package - Mini post

I realised that when I wrote this [post](https://callumgwtaylor.github.io/blog/2017/06/04/getting-data-from-humanitarian-data-exchange-in-a-reproducible-r-pipeline/), I should do something more sensible to share the code then put the text up in a blog. Writing a package seemed overkill though, and something you only do for 'real code'.

But curiousity got the better of me, and after reading the go-to [post](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) for package writing, I thought I might as well try.

So here we are: [hdxr](https://github.com/callumgwtaylor/hdxr)

It has the functions I mentioned before in the above post

`hdx_connect()`
`hdx_list()`
`hdx_package_search()`
`hdx_resource_list()`

How to use them is explained in the github repo and blog post above. There has been no testing whatsoever and I bet they wont work first try for you. If you want to let me know how to improve them or how to use ckanr better then I can be contacted on github or twitter.
